# Generated by Django 5.1.3 on 2024-12-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_calendarevent_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recipe_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recipe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
