"""
Django settings for ramu project.

Generated by 'django-admin startproject' using Django 5.1.2.
"""

from pathlib import Path
import os

# Base directory of the project (two levels up from this file)
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: Keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zqx)(4m606g6&f^)ko#450#w@!@n5f!0pb03zm=8kty947ms(_'

# SECURITY WARNING: Don't run with debug turned on in production!
DEBUG = True

# Define the hosts allowed to access the project
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'accounts',  # Custom app for user accounts
    'django.contrib.admin',  # Admin interface
    'django.contrib.auth',  # Authentication framework
    'django.contrib.contenttypes',  # Content type system
    'django.contrib.sessions',  # Session framework
    'django.contrib.messages',  # Messaging framework
    'django.contrib.staticfiles',  # Static file handling
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Security-related middleware
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session handling
    'django.middleware.common.CommonMiddleware',  # Common middleware for standard headers
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Authentication handling
    'django.contrib.messages.middleware.MessageMiddleware',  # Flash messages handling
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Protect against clickjacking
]

# Root URL configuration
ROOT_URLCONF = 'ramu.urls'  

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Use Django's template engine
        'DIRS': [BASE_DIR / 'templates'],  # Points to a global templates directory
        'APP_DIRS': True,  # Automatically look for templates inside app directories
        'OPTIONS': {
            'context_processors': [  # Define processors to add context variables to templates
                'django.template.context_processors.debug',  # Debug context
                'django.template.context_processors.request',  # Request context
                'django.contrib.auth.context_processors.auth',  # User authentication context
                'django.contrib.messages.context_processors.messages',  # Flash messages context
            ],
        },
    },
]

WSGI_APPLICATION = 'ramu.wsgi.application'

# Database configuration
# Using the locally setup PostgreSQL database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  
        'NAME': 'ramustore',  
        'USER': 'ramu',  
        'PASSWORD': 'kaka', 
        'HOST': 'localhost',  
        'PORT': '5432', 
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    # List of password validators can be added here for production
]

# Internationalization settings
LANGUAGE_CODE = 'en-us'  
TIME_ZONE = 'UTC' 
USE_I18N = True  
USE_TZ = True 

# API key for Spoonacular API
SPOONACULAR_API_KEY = "62c82155ebda44cbaeed4927ea08fdc9" 

# Static file settings
STATIC_URL = 'static/' 

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' 

# Authentication-related redirects
LOGIN_REDIRECT_URL = 'main_welcome'  # Redirect URL after login
LOGOUT_REDIRECT_URL = 'welcome'  # Redirect URL after logout